### ISSUE TITLE
Assembly example from source code gives "AttributeError: 'MultiDiGraph' object has no attribute 'node'" error

### ISSUE THREAD

**Issue by harijay** [BjornFJohansson/pydna#59]
I really like pydna and have been using it to check  my cloning strategy designs. Thank you for a very useful program.

I recently tried running the assembly example in the source code and get an error "AttributeError: 'MultiDiGraph' object has no attribute 'node'" details of which are pasted below.

I ran across the error when trying my own construct and [posted on the google Group](https://groups.google.com/forum/#!topic/pydna/NQd-VvWyePA). Apologies for the double post, but I am hoping it is something I am doing wrong while setting up the assembly.

Thanks
Hari

```
a = Dseqrecord("acgatgctatactgCCCCCtgtgctgtgctcta")
b = Dseqrecord("tgtgctgtgctctaTTTTTtattctggctgtatc")
c = Dseqrecord("tattctggctgtatcGGGGGtacgatgctatactg")
x = Assembly((a,b,c), limit=14)
x
x.assemble_circular()


AttributeError                            Traceback (most recent call last)
<ipython-input-35-b1ec03edd045> in <module>()
      4 x = Assembly((a,b,c), limit=14)
      5 x
----> 6 x.assemble_circular()

1 frames
/usr/local/lib/python3.6/dist-packages/pydna/assembly.py in <genexpr>(.0)
    342         cpaths_sorted=[]
    343         for cpath in cpaths:
--> 344             order, node = min((self.G.node[node]["order"],node) for node in cpath)
    345             i=cpath.index(node)
    346             cpaths_sorted.append((order, cpath[i:]+cpath[:i]))

AttributeError: 'MultiDiGraph' object has no attribute 'node'
```

**Comment by BjornFJohansson** [comment]
Hi, I did some experimenting and some searching, and it seems that pydna
does not work with networkx version 2.4. Please check if you have that?
The immediate solution is to downgrade to 2.3 for now. Meanwhile I will make another release to fix this.

**Comment by harijay** [comment]
Thanks a tonne @BjornFJohansson . I did have networkx version 2.4 which was the default on Google Collaboratory. I downgraded to 2.3

`!pip3 install networkx==2.3`

The assemblies then worked perfectly.
